// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkDL9mQAxKqQavh0UbUdu0u79RkhQ96Dg',
    appId: '1:1093654144892:web:81bcdadd5f0c0aa91ca6f9',
    messagingSenderId: '1093654144892',
    projectId: 'lab10-967c8',
    authDomain: 'lab10-967c8.firebaseapp.com',
    storageBucket: 'lab10-967c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjmAufzJlinqldVIQYxarCmEIA7cCa0Z4',
    appId: '1:1093654144892:android:772ad54c40a7bfb71ca6f9',
    messagingSenderId: '1093654144892',
    projectId: 'lab10-967c8',
    storageBucket: 'lab10-967c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk3Tz1E6xmcNNI-WiZ5qo1XMc2VIZn-VM',
    appId: '1:1093654144892:ios:0e0dd2219043d7d31ca6f9',
    messagingSenderId: '1093654144892',
    projectId: 'lab10-967c8',
    storageBucket: 'lab10-967c8.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk3Tz1E6xmcNNI-WiZ5qo1XMc2VIZn-VM',
    appId: '1:1093654144892:ios:0e0dd2219043d7d31ca6f9',
    messagingSenderId: '1093654144892',
    projectId: 'lab10-967c8',
    storageBucket: 'lab10-967c8.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkDL9mQAxKqQavh0UbUdu0u79RkhQ96Dg',
    appId: '1:1093654144892:web:ff04400187dbacbd1ca6f9',
    messagingSenderId: '1093654144892',
    projectId: 'lab10-967c8',
    authDomain: 'lab10-967c8.firebaseapp.com',
    storageBucket: 'lab10-967c8.appspot.com',
  );
}
